### ISSUE TITLE
Docs unusable on Android

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1062]
The docs site is unusable for me with Chrome 28.0.1500.94 on Android 4.1.1.

When a page starts loading, it looks like it might be barely usable:

![](https://cloud.githubusercontent.com/assets/287848/18728145/3793fa62-804c-11e6-9fa5-3cafb5d6805c.png)

But then, page content is covered by a large dark rectangle, which looks like it corresponds to the page footer (the screenshot shown is zoomed out):

![](https://cloud.githubusercontent.com/assets/287848/18728269/d396b292-804c-11e6-9405-e118c5a6bfec.png)

Sometimes, the rectangle does not span the whole page, but then text is shown one character per line:

![](https://cloud.githubusercontent.com/assets/287848/18728285/ebcb48fa-804c-11e6-8180-0cceb2f1846e.png)

**Comment by mairaw** [comment]
@DuncanmaMSFT can you follow up on this?

**Comment by mairaw** [comment]
I've also opened an internal bug to track this.

**Comment by mairaw** [comment]
@svick can you still repro this? I'm asking because I was having a similar issue on Safari/iPhone and that is now gone.

**Comment by svick** [comment]
@mairaw Yes, it still behaves the same for me.

**Comment by mairaw** [comment]
Ok, thanks for confirming @svick!

**Comment by mairaw** [comment]
@svick the internal bug was resolved as fixed. can you please check if it still repros? thanks!

**Comment by svick** [comment]
It still repros for me. Though the version of Chrome I'm using is ancient, so I'm not sure how important it is to fix this.

I tried to see how it looks on other devices using browserstack.com and it seems many older devices still have this issue: https://www.browserstack.com/screenshots/d344d829081ca69b3cb90984249b91d87368eb0d.

**Comment by mairaw** [comment]
This site is awesome. I didn't know about it!

**Comment by mairaw** [comment]
@svick can you please test this again? Team says they have fixed this now.

**Comment by svick** [comment]
Yes, it works fine for me now. Thanks to the team for making it work.
