### ISSUE TITLE
Incorrect documentation on AsSpan method.

### ISSUE THREAD

**Issue by kshyju** [dotnet/docs#12594]
As per the [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.internal.system.spanextensions.asspan?view=aspnetcore-2.0&viewFallbackFrom=aspnetcore-2.2#Microsoft_AspNetCore_Server_Kestrel_Internal_System_SpanExtensions_AsSpan_System_String_), The `AsSpan` method will throw a `System.ArgumentNullException` exception when the input text is `null`. I found it to be returning an empty span instead of throwing an exception.

Perhaps we need to fix the documentation ?

![image](https://user-images.githubusercontent.com/144469/58649717-b5171a80-82c1-11e9-970d-c91f724c41ef.png)

.net core app 2.2 is my version.

> Assembly System.Memory, Version=4.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> microsoft.netcore.app\2.2.0\ref\netcoreapp2.2\System.Memory.dll

**Comment by kshyju** [comment]
cc @terrajobst

**Comment by svick** [comment]
You linked to the documentation for the ASP.NET Core 2.0 method `Microsoft.AspNetCore.Server.Kestrel.Internal.System.SpanExtensions.AsSpan`. But if you're on .Net Core 2.2, then you're using the "real" `System.MemoryExtensions.AsSpan`, [whose documentation does not claim it throws when the input is `null`](https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.asspan?view=netcore-2.2#System_MemoryExtensions_AsSpan_System_String_) (though it doesn't really claim anything, which should be fixed).

How did you find that page? If it's likely that others will confuse the two versions of `AsSpan` too, it might make sense to do something about that (like adding a note to the ASP.NET Core "Internal" version).

**Comment by kshyju** [comment]
Thanks!

This 2.0 version came in my bing search for the API documentation. I tried choosing 2.2 in the left side dropdown and it reloaded the page saying "you have been redirected to the newest product version this page is available for". The dropdown still shows 2.0

![image](https://user-images.githubusercontent.com/144469/58655329-bef34a80-82ce-11e9-9fc4-66dd254e9706.png)

**Comment by Thraka** [comment]
> This 2.0 version came in my bing search for the API documentation. I tried choosing 2.2 in the left side dropdown and it reloaded the page saying "you have been redirected to the newest product version this page is available for". The dropdown still shows 2.0

This just because you landed on the ASP.NET API site itself. So you'll only see versions for that product stack. This `AsSpan` doc for the .NET Core stack has not yet been documented by the product team. I'm going to close this issue.

Thanks!
