### ISSUE TITLE
Where is the explanation of the severity levels?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#22178]
On the TextEditor -> C# -> CodeStyle -> Formatting -> Naming config page there is a “Refactoring Only” option for Severity. What does it do?
![image](https://user-images.githubusercontent.com/15381181/103302098-d0339a00-49d0-11eb-85be-51f7f7cb0fdc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c8357d-11a6-6f12-b044-5ff44df65d10
* Version Independent ID: 0c103fd7-5cc4-2726-40f8-d759419ae635
* Content: [.NET code style rule options - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019)
* Content Source: [docs/fundamentals/code-analysis/code-style-rule-options.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/code-style-rule-options.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by dennistouchet** [comment]
I will check this out as soon as I have a moment, but maybe it's an option that only appears in the `Context Menu` under `refactor`?

**Comment by gewarren** [comment]
This info would be more appropriate in the VS docs, perhaps in [this section](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?toc=%2Fvisualstudio%2Fcode-quality%2Ftoc.json&view=vs-2019#code-styles-in-the-options-dialog-box). Also, there's a link to what severity levels mean in the VS IDE in the green Tip box [here](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#severity-level), but it redirects back to the .NET docs. Once we have the info for the VS severity levels documented, we should fix that link to point to it. @TerryGLee @Mikejo5000 Do you want me to transfer this issue to MicrosoftDocs/visualstudio-docs?

**Comment by StingyJack** [comment]
@gewarren  that page does have some of the info I needed but I still dont see what "Refactoring Only" means or does.  When searching for "Refactoring Only" in all of MS VS IDE documentation this article is the only mention of it.

**Comment by gewarren** [comment]
Here's the [VS descriptions](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/release-16.7/docs/ide/editorconfig-language-conventions.md#severity-levels) that have since been deleted. The "Refactoring Only" option corresponds to "silent" in this table.

**Comment by Mikejo5000** [comment]
Looks fine to transfer this, Genevieve.

**Comment by gewarren** [comment]
This issue was moved to MicrosoftDocs/visualstudio-docs#6263
