### ISSUE TITLE
<remove> and <clear> are not work in <configSections>

### ISSUE THREAD

**Issue by qiaoxingxing** [dotnet/docs#3708]
I follow this [docs/clear-element-for-configsections.md at master · dotnet/docs](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/clear-element-for-configsections.md)
this is my app.config file
```
<configSections>
  <clear/>
  <remove name="oracle.manageddataaccess.client" />
  <section name="oracle.manageddataaccess.client" type="OracleInternal.Common.ODPMSectionHandler, Oracle.ManagedDataAccess" />

```
but I still get error 
> System.Configuration.ConfigurationErrorsException: Section or group name 'oracle.manageddataaccess.client" is already defined. Updates to this may only occur at the configuration level where it is defined.

I have found this [ASP.NET MVC Web.Config <configSections> inheritance problem | Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/434335/asp-net-mvc-web-config-configsections-inheritance-problem)

> clear  and remove  were never implemented for configSections and sectionGroups because of the difficulty involved attempting to merge different definitions of the same section-handlers and section groups.

I don't which is right.

**Comment by mairaw** [comment]
@qiaoxingxing thanks for reporting the issue. The Connect bug probably has the right information. 

@davidfowl @danroth27 who could we talk to confirm the config section behavior for ASP.NET? Thanks.

**Comment by danroth27** [comment]
@csharpfritz Can you help direct this to the right folks?

**Comment by csharpfritz** [comment]
We should connect with @StephenMolloy and @HongGit for triage

**Comment by dsidirop** [comment]
Can confirm that this bug affects Web.config files of ASP.NET MVC5 projects target .net4.7.1

**Comment by bcumberledge** [comment]
will this be fixed?

**Comment by qacollective** [comment]
Action on this problem would appear justified given the amount of angst it seems to be causing:

https://stackoverflow.com/questions/4030891/how-to-prevent-inheritance-for-web-config-file-for-configsections
https://stackoverflow.com/questions/1572326/how-to-stop-inheritance-of-configsectionsin-web-config
https://stackoverflow.com/questions/367282/disable-web-config-inheritance
https://stackoverflow.com/questions/23367347/entry-has-already-been-added-two-separate-app-pools/24260655#24260655

**Comment by StephenMolloy** [comment]
As the original issue report points out, remove and clear were never implemented. They haven't existed since before 2.0, and I doubt they existed before that. The documentation should be fixed, but I don't see these features being implemented at this point.

**Comment by bcumberledge** [comment]
There should be a simple solution then to stop inheriting.   Nothing works
right now to cover the entire config, not even altering the definition of
the app pool to not allow it.

**Comment by szalapski** [comment]
I am also experiencing this.  I don't want to stop inheritance from the machine.config side--I want to override this section on the web.config side, just as qiaoxingxing wrote.

**Comment by Tridus** [comment]
Still having this problem, and the documentation is still wrong. Can that at least be corrected?

**Comment by StephenMolloy** [comment]
These will never be implemented. So please don't hold out hope that they will.

The docs should be updated though. @Rick-Anderson, do you know who would be able to fix the docs to reflect that 'remove' and 'clear' aren't a thing in the 'configSections' area of config?

**Comment by Rick-Anderson** [comment]
@StephenMolloy  I can take care of it.

@gewarren  my plan is to update the remarks to say these elements do ***not*** clear/remove . I'll delete the **Example**
In **Configuration file**, I'll say these don't clear/remove

[`<remove> element for <configSections>`](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/remove-element-for-configsections)
