### ISSUE TITLE
Add the using statements

### ISSUE THREAD

**Issue by billycamp** [dotnet/docs#7647]
Fine example, but from a cosmetic perspective, I'd just add the using System.Collections.Generic; and using System.Console; to the top of the code example to avoid the unattractive fully qualified type names...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2cb228-430f-43a7-4447-85d21d2de420
* Version Independent ID: 2af9e215-97f2-fb66-1090-591e83fbda92
* Content: [How to: Use a Dictionary to Store Event Instances (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances)
* Content Source: [docs/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/events/how-to-use-a-dictionary-to-store-event-instances.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @billycamp 
I agree that following the general convention for using statements would make a better sample. I've added this to our backlog and the community contribution project. If you'd like to create a PR to update this article, I'll watch for it.

**Comment by billycamp** [comment]
Hi Bill,

Tried to create a PR for this but auth failed (in GitHub desktop) when I pushed the branch with changes.  I have attached a file with the following changes:

Changes:
Included using directives
Added Namespace
Changed the hardcoded "Event#" strings to use private string variables

included file docs\csharp\programming-guide\events\codesnippet\CSharp\how-to-use-a-dictionary-to-store-event-instances_1.cs

Verified that attached file builds clean in VS2017

Thanks,
Wil Campbell

________________________________

**Comment by BillWagner** [comment]
@billycamp Those changes look good.

If you want to create the PR, you'll need to fork this repository to your own account, and then create the changes in your fork.  Our [Contributor guide](https://docs.microsoft.com/contribute/get-started-setup-local) has instructions.  Or, I can create a PR with the above changes

Let me know which you want to do.

**Comment by billycamp** [comment]
I'll read the proccess and give creating the PR a go later tonight - thanks!


-------- Original message --------

**Comment by Niladri24dutta** [comment]
@BillWagner @rpetrusha Can I submit a PR for this? It seems this is not resolved yet.

**Comment by BillWagner** [comment]
@Niladri24dutta Yes, we'd appreciate a PR.
